"""empty message

Revision ID: c18ceb763848
Revises: 
Create Date: 2020-05-25 22:36:49.052995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c18ceb763848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'password_hash')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('roles', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
